version: '3'
services:
  api:
    build: .
    ports:
    - "5000:5000"
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: mariucaa
      MYSQL_DATABASE: pisic
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql 

volumes:
  mysql-data:  